### PR TITLE
👌 IMPROVE: closing array

### PR DESCRIPTION
**Pull request by colorful-tones**
Lesson three was throwing a small parse error for me. It seems that one of the arrays was not closed properly.

This addresses that. 

Thanks for creating this awesome course @aurooba 
You're helping so many in the community up their game. 👏

### CODE REVIEW

**Comment by aurooba** [comment]
Oh man, I can't believe my lint tool somehow missed the wrong bracket, thanks for the catch! I do want to check the `!important` issue first, but definitely shall pull in the fix for the closing bracket.

**Comment by colorful-tones** [comment]
> I do want to check the !important issue first, but definitely shall pull in the fix for the closing bracket.

Sorry, I'm being lazy and working off of Github site directly for my Pull Request and did not realize I was adding these commits to my original PR. 🤦  

(not the way I usually work, and was just trying to save a few minutes, which never works out in the end 😄 )

**Comment by aurooba** [comment]
> Sorry, I'm being lazy and working off of Github site directly for my Pull Request and did not realize I was adding these commits to my original PR. 🤦

Been there, done that. I get it. :)

**Comment by aurooba** [comment]
I've included your array bug improvement and credit to you. Couldn't merge this because of the other changes. :)

**Pull request closed without merging**
